name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install direnv
        run: sudo apt-get install -y direnv

      - name: Load environment variables
        env:
          DB_ADDR: ${{ secrets.DB_ADDR }} # Add other secrets here
        run: |
          echo "DB_ADDR=${DB_ADDR}" >> .envrc
          direnv allow .

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Verify Dependencies
        run: make vendor

      - name: Run Audit
        run: make audit

      - name: Build API
        run: make build/api

      - name: Run Tests
        run: make test
